workflows:
  native-android:
    name: Native Android
    instance_type: mac_mini
    max_build_duration: 120
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build Android test APK
        script: |
          ./gradlew assembleAndroidTest
      - name: Setup Firebase Test Lab
        script: |
          set -ex
          echo $GCLOUD_KEY_FILE > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quiet config set project $FIREBASE_PROJECT
      - name: Test
        script: |
          gcloud firebase test android run tests.yml:sunflower-medium
    artifacts:
      - app/build/outputs/**/*.apk
