workflows:
  native-android:
    name: Native Android
    instance_type: mac_mini
    max_build_duration: 120
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build Android test APK
        script: |
          ./gradlew assembleAndroidTest
      - name: Setup emulator.wtf
        script: |
          curl https://maven.emulator.wtf/releases/ew-cli -o ew-cli
          chmod a+x ew-cli
      - name: Test
        script: |
          ./ew-cli tests.yml:sunflower-medium --outputs-dir results
        test_report: results/**/*.xml
    artifacts:
      - app/build/outputs/**/*.apk
