workflows:
    native-android:
        name: Native Android
        instance_type: linux
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
        scripts:
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
            - name: Build Android debug APK
              script: |
                ./gradlew assembleDebug
            - name: Build Android test APK
              script: |
                ./gradlew assembleAndroidTest
        artifacts:
            - app/build/outputs/**/*.apk
