workflows:
  native-android:
    name: Native Android
    environment:
      groups:
        - EMULATORWTF
    instance_type: mac_pro
    max_build_duration: 120
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Run ew-cli --help
        script: |
#      - name: Build Android debug and test APKs
#        script: |
#          ./gradlew assembleDebug assembleAndroidTest
#      - name: Setup emulator.wtf
#        script: |
#          curl https://maven.emulator.wtf/releases/ew-cli -o ew-cli
#          chmod a+x ew-cli
#      - name: Test
#        script: ew-cli tests.yml:sunflower-medium --outputs-dir results
#        test_report: results/**/*.xml
>>>>>>> temp: run only ew-cli --help
    artifacts:
      - app/build/outputs/**/*.apk
