workflows:
  native-android:
    name: Native Android
    instance_type: mac_pro
    max_build_duration: 120
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build Android test APK
        script: |
          ./gradlew assembleAndroidTest
      - name: Launch emulator
        script: |
          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
          adb shell getprop > emulator.props.txt
      - name: Test
        script: |
          set -e
          adb install -r ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          adb install -r ./app/build/outputs/apk/debug/app-debug.apk
          adb install -r ./orchestrator-1.4.1.apk
          adb install -r ./test-services-1.4.1.apk
          adb shell 'CLASSPATH=$(pm path androidx.test.services)' app_process / androidx.test.services.shellexecutor.ShellMain am instrument -r -w -e size medium -e clearPackageData true -e debug false -e targetInstrumentation com.google.samples.apps.sunflower.test/com.google.samples.apps.sunflower.utilities.MainTestRunner androidx.test.orchestrator/androidx.test.orchestrator.AndroidTestOrchestrator
          adb logcat -d > emulator.log
    artifacts:
      - app/build/outputs/**/*.apk
      - emulator.log
      - emulator.props.txt
