version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  test:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2022.04.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Build apks
          command: ./gradlew assembleDebug assembleAndroidTest
      - android/save-gradle-cache
      - android/save-build-cache

workflows:
  test:
    jobs:
      - test
