version: 2.1

orbs:
  android: circleci/android@2.1.2
  emulatorwtf: emulator-wtf/run-tests@dev:alpha

jobs:
  test:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2022.04.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Build apks
          command: ./gradlew assembleDebug assembleAndroidTest
      - android/save-gradle-cache
      - android/save-build-cache
      - emulatorwtf/run-tests:
          app: app/build/outputs/apk/debug/app-debug.apk
          test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          use_orchestrator: true
          clear_package_data: true
          environment_variables: size=medium
          outputs_dir: /tmp/test/outputs
      - store_test_results:
        path: /tmp/test/outputs

workflows:
  test:
    jobs:
      - test:
          context:
            - emulator-wtf
